/**
 * Export Configuration
 *
 * Centralized configuration for all export types (PDF, PPT, CSV).
 * Customize branding, sections, and behavior based on export context.
 */

// =============================================================================
// BRANDING CONFIGURATION
// =============================================================================

export interface BrandingConfig {
  // Logo (base64 encoded or URL path)
  logo?: string;
  logoWidth?: number;  // in mm for PDF, inches for PPT
  logoHeight?: number;

  // Colors (hex without #)
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  textColor: string;
  mutedTextColor: string;

  // Company info
  companyName: string;
  tagline?: string;
  website?: string;

  // Footer
  footerText: string;
  showGeneratedDate: boolean;
}

// Placeholder FuseIQ logo as base64 SVG
// Replace this with your actual logo by converting to base64
// You can use: https://base64.guru/converter/encode/image
const FUSEIQ_LOGO_PLACEHOLDER = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTYwIiBoZWlnaHQ9IjQwIiB2aWV3Qm94PSIwIDAgMTYwIDQwIiBmaWxsPSJub25lIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPgo8cmVjdCB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIHJ4PSI4IiBmaWxsPSIjN0MzQUVEIi8+CjxwYXRoIGQ9Ik0xMiAxMkgyOFYxNkgxMlYxMloiIGZpbGw9IndoaXRlIi8+CjxwYXRoIGQ9Ik0xMiAxOEgyNFYyMkgxMlYxOFoiIGZpbGw9IndoaXRlIi8+CjxwYXRoIGQ9Ik0xMiAyNEgyMFYyOEgxMlYyNFoiIGZpbGw9IndoaXRlIi8+Cjx0ZXh0IHg9IjUwIiB5PSIyOCIgZm9udC1mYW1pbHk9IkFyaWFsLCBzYW5zLXNlcmlmIiBmb250LXNpemU9IjI0IiBmb250LXdlaWdodD0iYm9sZCIgZmlsbD0iIzdDM0FFRCI+RnVzZTwvdGV4dD4KPHRleHQgeD0iMTA1IiB5PSIyOCIgZm9udC1mYW1pbHk9IkFyaWFsLCBzYW5zLXNlcmlmIiBmb250LXNpemU9IjI0IiBmb250LXdlaWdodD0iYm9sZCIgZmlsbD0iIzFGMjkzNyI+SVE8L3RleHQ+Cjwvc3ZnPg==';

export const DEFAULT_BRANDING: BrandingConfig = {
  // FuseIQ placeholder logo - replace with actual logo
  logo: FUSEIQ_LOGO_PLACEHOLDER,
  logoWidth: 40,
  logoHeight: 12,

  // FuseIQ purple theme
  primaryColor: '7C3AED',    // Purple 600
  secondaryColor: '8B5CF6',  // Purple 500
  accentColor: '10B981',     // Emerald 500
  textColor: '1F2937',       // Gray 800
  mutedTextColor: '6B7280',  // Gray 500

  companyName: 'FuseIQ',
  tagline: 'Intelligent Media Planning',
  website: 'fuseiq.com',

  footerText: 'Generated by FuseIQ Media Planner',
  showGeneratedDate: true,
};

// =============================================================================
// EXPORT TYPES & CONTEXTS
// =============================================================================

export type ExportType =
  | 'MEDIA_PLAN'           // Pre-campaign planning document
  | 'CAMPAIGN_BRIEF'       // Executive summary for stakeholders
  | 'POST_CAMPAIGN'        // Performance analysis after campaign
  | 'DATA_APPEND'          // Audience/segment data export
  | 'ATTRIBUTION_REPORT'   // Multi-touch attribution analysis
  | 'FORECAST_REPORT'      // Predictive analytics & forecasts
  | 'PORTFOLIO_SUMMARY'    // Multi-campaign overview
  | 'FLIGHT_DETAIL';       // Single flight breakdown

export type ExportFormat = 'PDF' | 'PPT' | 'CSV' | 'XLSX';

// Context determines which export type is appropriate
export interface ExportContext {
  // Where in the app the export was triggered
  source: 'campaign' | 'flight' | 'plan' | 'portfolio' | 'attribution' | 'analytics';

  // Current stage
  stage: 'planning' | 'active' | 'completed' | 'analysis';

  // What data is available
  hasPerformanceData: boolean;
  hasAttributionData: boolean;
  hasForecastData: boolean;
}

// Map context to recommended export type
export function getRecommendedExportType(context: ExportContext): ExportType {
  const { source, stage, hasPerformanceData } = context;

  if (source === 'attribution') return 'ATTRIBUTION_REPORT';
  if (source === 'portfolio') return 'PORTFOLIO_SUMMARY';
  if (source === 'analytics' && hasPerformanceData) return 'POST_CAMPAIGN';

  if (stage === 'completed' && hasPerformanceData) return 'POST_CAMPAIGN';
  if (stage === 'planning') return 'MEDIA_PLAN';
  if (stage === 'active') return 'CAMPAIGN_BRIEF';

  return 'MEDIA_PLAN';
}

// =============================================================================
// SECTION CONFIGURATION
// =============================================================================

export type SectionType =
  | 'title'
  | 'executive_summary'
  | 'budget_overview'
  | 'placement_table'
  | 'channel_breakdown'
  | 'channel_chart'
  | 'timeline_gantt'
  | 'audience_summary'
  | 'performance_metrics'
  | 'performance_chart'
  | 'attribution_models'
  | 'attribution_chart'
  | 'recommendations'
  | 'next_steps'
  | 'appendix';

export interface SectionConfig {
  type: SectionType;
  enabled: boolean;
  title?: string;        // Override default title
  order: number;         // Sort order
  pageBreakBefore?: boolean;
  options?: Record<string, unknown>;  // Section-specific options
}

// =============================================================================
// EXPORT TYPE CONFIGURATIONS
// =============================================================================

export interface ExportTypeConfig {
  name: string;
  description: string;
  supportedFormats: ExportFormat[];
  sections: SectionConfig[];
}

export const EXPORT_TYPE_CONFIGS: Record<ExportType, ExportTypeConfig> = {
  MEDIA_PLAN: {
    name: 'Media Plan',
    description: 'Comprehensive pre-campaign planning document with placement details',
    supportedFormats: ['PDF', 'PPT', 'XLSX'],
    sections: [
      { type: 'title', enabled: true, order: 1 },
      { type: 'executive_summary', enabled: true, order: 2 },
      { type: 'budget_overview', enabled: true, order: 3 },
      { type: 'channel_breakdown', enabled: true, order: 4 },
      { type: 'channel_chart', enabled: true, order: 5 },
      { type: 'timeline_gantt', enabled: true, order: 6, pageBreakBefore: true },
      { type: 'placement_table', enabled: true, order: 7, pageBreakBefore: true },
      { type: 'audience_summary', enabled: true, order: 8 },
      { type: 'recommendations', enabled: false, order: 9 },
    ],
  },

  CAMPAIGN_BRIEF: {
    name: 'Campaign Brief',
    description: 'Executive summary for stakeholder presentations',
    supportedFormats: ['PDF', 'PPT'],
    sections: [
      { type: 'title', enabled: true, order: 1 },
      { type: 'executive_summary', enabled: true, order: 2 },
      { type: 'budget_overview', enabled: true, order: 3 },
      { type: 'channel_chart', enabled: true, order: 4 },
      { type: 'timeline_gantt', enabled: true, order: 5 },
      { type: 'next_steps', enabled: true, order: 6 },
    ],
  },

  POST_CAMPAIGN: {
    name: 'Post-Campaign Report',
    description: 'Performance analysis and insights after campaign completion',
    supportedFormats: ['PDF', 'PPT', 'XLSX'],
    sections: [
      { type: 'title', enabled: true, order: 1 },
      { type: 'executive_summary', enabled: true, order: 2 },
      { type: 'performance_metrics', enabled: true, order: 3 },
      { type: 'performance_chart', enabled: true, order: 4 },
      { type: 'channel_breakdown', enabled: true, order: 5, pageBreakBefore: true },
      { type: 'placement_table', enabled: true, order: 6,
        options: { showPerformance: true, showVariance: true } },
      { type: 'attribution_models', enabled: true, order: 7, pageBreakBefore: true },
      { type: 'recommendations', enabled: true, order: 8 },
      { type: 'appendix', enabled: true, order: 9, pageBreakBefore: true },
    ],
  },

  DATA_APPEND: {
    name: 'Data Append Export',
    description: 'Audience segment and targeting data for external systems',
    supportedFormats: ['CSV', 'XLSX'],
    sections: [
      { type: 'audience_summary', enabled: true, order: 1 },
      { type: 'placement_table', enabled: true, order: 2,
        options: { includeSegments: true, includeTargeting: true } },
    ],
  },

  ATTRIBUTION_REPORT: {
    name: 'Attribution Report',
    description: 'Multi-touch attribution analysis across channels',
    supportedFormats: ['PDF', 'PPT'],
    sections: [
      { type: 'title', enabled: true, order: 1, title: 'Attribution Analysis' },
      { type: 'executive_summary', enabled: true, order: 2 },
      { type: 'attribution_models', enabled: true, order: 3 },
      { type: 'attribution_chart', enabled: true, order: 4 },
      { type: 'channel_breakdown', enabled: true, order: 5,
        options: { showAttribution: true } },
      { type: 'recommendations', enabled: true, order: 6 },
    ],
  },

  FORECAST_REPORT: {
    name: 'Forecast Report',
    description: 'Predictive analytics and performance projections',
    supportedFormats: ['PDF', 'PPT'],
    sections: [
      { type: 'title', enabled: true, order: 1, title: 'Performance Forecast' },
      { type: 'executive_summary', enabled: true, order: 2 },
      { type: 'performance_chart', enabled: true, order: 3,
        options: { showForecast: true, showConfidenceInterval: true } },
      { type: 'channel_breakdown', enabled: true, order: 4 },
      { type: 'recommendations', enabled: true, order: 5 },
    ],
  },

  PORTFOLIO_SUMMARY: {
    name: 'Portfolio Summary',
    description: 'Multi-campaign overview and cross-campaign analytics',
    supportedFormats: ['PDF', 'PPT', 'XLSX'],
    sections: [
      { type: 'title', enabled: true, order: 1, title: 'Portfolio Overview' },
      { type: 'executive_summary', enabled: true, order: 2 },
      { type: 'budget_overview', enabled: true, order: 3,
        options: { showAllCampaigns: true } },
      { type: 'performance_chart', enabled: true, order: 4,
        options: { compareCampaigns: true } },
      { type: 'channel_breakdown', enabled: true, order: 5 },
      { type: 'recommendations', enabled: true, order: 6 },
    ],
  },

  FLIGHT_DETAIL: {
    name: 'Flight Detail',
    description: 'Detailed breakdown of a single flight',
    supportedFormats: ['PDF', 'XLSX'],
    sections: [
      { type: 'title', enabled: true, order: 1 },
      { type: 'budget_overview', enabled: true, order: 2 },
      { type: 'placement_table', enabled: true, order: 3 },
      { type: 'audience_summary', enabled: true, order: 4 },
    ],
  },
};

// =============================================================================
// CHART CONFIGURATION
// =============================================================================

export interface ChartConfig {
  type: 'bar' | 'pie' | 'line' | 'donut' | 'stacked_bar' | 'gantt';
  colors: string[];  // Array of hex colors
  showLegend: boolean;
  showValues: boolean;
  showPercentages: boolean;
}

export const DEFAULT_CHART_CONFIG: ChartConfig = {
  type: 'bar',
  colors: [
    '7C3AED',  // Purple
    '3B82F6',  // Blue
    '10B981',  // Green
    'F59E0B',  // Amber
    'EF4444',  // Red
    'EC4899',  // Pink
    '6366F1',  // Indigo
    '14B8A6',  // Teal
  ],
  showLegend: true,
  showValues: true,
  showPercentages: false,
};

// =============================================================================
// TABLE STYLING
// =============================================================================

export interface TableStyleConfig {
  headerBackground: string;
  headerTextColor: string;
  alternateRowBackground: string;
  borderColor: string;
  fontSize: number;
}

export const DEFAULT_TABLE_STYLE: TableStyleConfig = {
  headerBackground: '7C3AED',
  headerTextColor: 'FFFFFF',
  alternateRowBackground: 'F9FAFB',
  borderColor: 'E5E7EB',
  fontSize: 9,
};

// =============================================================================
// MASTER EXPORT CONFIG
// =============================================================================

export interface ExportConfig {
  branding: BrandingConfig;
  tableStyle: TableStyleConfig;
  chartConfig: ChartConfig;

  // PDF-specific
  pdf: {
    pageSize: 'letter' | 'a4';
    orientation: 'portrait' | 'landscape';
    margins: { top: number; right: number; bottom: number; left: number };
  };

  // PPT-specific
  ppt: {
    layout: 'LAYOUT_16x9' | 'LAYOUT_4x3';
    masterSlide?: string;  // Template name if using custom
  };
}

export const DEFAULT_EXPORT_CONFIG: ExportConfig = {
  branding: DEFAULT_BRANDING,
  tableStyle: DEFAULT_TABLE_STYLE,
  chartConfig: DEFAULT_CHART_CONFIG,

  pdf: {
    pageSize: 'letter',
    orientation: 'portrait',
    margins: { top: 20, right: 14, bottom: 20, left: 14 },
  },

  ppt: {
    layout: 'LAYOUT_16x9',
  },
};

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

export function getEnabledSections(exportType: ExportType): SectionConfig[] {
  const config = EXPORT_TYPE_CONFIGS[exportType];
  return config.sections
    .filter(s => s.enabled)
    .sort((a, b) => a.order - b.order);
}

export function isFormatSupported(exportType: ExportType, format: ExportFormat): boolean {
  return EXPORT_TYPE_CONFIGS[exportType].supportedFormats.includes(format);
}

export function getAvailableExportTypes(context: ExportContext): ExportType[] {
  const types: ExportType[] = [];

  // Always available
  types.push('MEDIA_PLAN');
  types.push('CAMPAIGN_BRIEF');

  if (context.source === 'flight') {
    types.push('FLIGHT_DETAIL');
  }

  if (context.source === 'portfolio') {
    types.push('PORTFOLIO_SUMMARY');
  }

  if (context.hasPerformanceData) {
    types.push('POST_CAMPAIGN');
  }

  if (context.hasAttributionData) {
    types.push('ATTRIBUTION_REPORT');
  }

  if (context.hasForecastData) {
    types.push('FORECAST_REPORT');
  }

  // Data append always available for data export
  types.push('DATA_APPEND');

  return types;
}
