/**
 * PDF Generator
 *
 * Generates PDF exports using configurable sections and branding.
 */

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { MediaPlan } from '../types';
import {
  ExportType,
  ExportConfig,
  DEFAULT_EXPORT_CONFIG,
  EXPORT_TYPE_CONFIGS,
  getEnabledSections,
} from '../config/exportConfig';
import { PDFContext, ExportData, renderPDFSection } from './exportSections';

// =============================================================================
// MAIN EXPORT FUNCTION
// =============================================================================

export interface PDFExportOptions {
  exportType?: ExportType;
  config?: Partial<ExportConfig>;
  filename?: string;
}

export const generateMediaPlanPDF = (
  mediaPlan: MediaPlan,
  options: PDFExportOptions = {}
) => {
  const {
    exportType = 'MEDIA_PLAN',
    config: customConfig,
    filename,
  } = options;

  // Merge custom config with defaults
  const config: ExportConfig = {
    ...DEFAULT_EXPORT_CONFIG,
    ...customConfig,
    branding: { ...DEFAULT_EXPORT_CONFIG.branding, ...customConfig?.branding },
    pdf: { ...DEFAULT_EXPORT_CONFIG.pdf, ...customConfig?.pdf },
  };

  const { campaign } = mediaPlan;

  // Create PDF document
  const doc = new jsPDF({
    orientation: config.pdf.orientation,
    unit: 'mm',
    format: config.pdf.pageSize,
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Initialize context
  const ctx: PDFContext = {
    doc,
    branding: config.branding,
    tableStyle: config.tableStyle,
    chartConfig: config.chartConfig,
    currentY: config.pdf.margins.top,
    pageWidth,
    pageHeight,
    margins: config.pdf.margins,
  };

  // Prepare data
  const data: ExportData = {
    mediaPlan,
    campaign,
    placements: campaign.placements,
  };

  // Get enabled sections for this export type
  const sections = getEnabledSections(exportType);

  // Render each section
  sections.forEach((sectionConfig, index) => {
    // Check if we need a page break
    if (sectionConfig.pageBreakBefore && index > 0) {
      doc.addPage();
      ctx.currentY = config.pdf.margins.top;
    }

    // Check if we're running low on page space
    if (ctx.currentY > pageHeight - 40) {
      doc.addPage();
      ctx.currentY = config.pdf.margins.top;
    }

    // Render the section
    ctx.currentY = renderPDFSection(ctx, sectionConfig.type, data, sectionConfig);
  });

  // Add footer to all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(`#${config.branding.mutedTextColor}`);

    // Footer text
    doc.text(
      config.branding.footerText,
      config.pdf.margins.left,
      pageHeight - 10
    );

    // Page number
    doc.text(
      `Page ${i} of ${totalPages}`,
      pageWidth - config.pdf.margins.right - 20,
      pageHeight - 10
    );
  }

  // Generate filename
  const exportName = filename ||
    `${campaign.name.replace(/\s+/g, '_')}_${exportType}_${new Date().toISOString().split('T')[0]}.pdf`;

  doc.save(exportName);
};

// =============================================================================
// LEGACY FUNCTION (for backward compatibility)
// =============================================================================

export const generateSimplePDF = (mediaPlan: MediaPlan) => {
  const doc = new jsPDF();
  const { campaign } = mediaPlan;

  // Title
  doc.setFontSize(20);
  doc.text('Media Plan Export', 14, 22);

  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text(`Client: ${campaign.advertiser}`, 14, 32);
  doc.text(`Campaign: ${campaign.name}`, 14, 38);
  doc.text(`Budget: $${campaign.budget.toLocaleString()}`, 14, 44);
  doc.text(`Dates: ${campaign.startDate} to ${campaign.endDate}`, 14, 50);

  // Stats
  doc.text(`Total Spend: $${mediaPlan.totalSpend.toLocaleString()}`, 140, 32);
  doc.text(`Remaining: $${mediaPlan.remainingBudget.toLocaleString()}`, 140, 38);

  // Placements Table
  const tableData = (campaign.placements || []).map(p => [
    p.channel,
    p.vendor,
    p.adUnit,
    `${p.startDate} - ${p.endDate}`,
    `$${p.rate.toLocaleString()} / ${p.costMethod}`,
    p.quantity.toLocaleString(),
    `$${p.totalCost.toLocaleString()}`
  ]);

  autoTable(doc, {
    head: [['Channel', 'Vendor', 'Ad Unit', 'Dates', 'Rate', 'Qty', 'Cost']],
    body: tableData,
    startY: 60,
    theme: 'grid',
    styles: { fontSize: 8 },
    headStyles: { fillColor: [124, 58, 237] }
  });

  // Footer
  const finalY = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable?.finalY || 60;
  doc.setFontSize(10);
  doc.text('Generated by FuseIQ Media Planner', 14, finalY + 10);

  doc.save(`${campaign.name.replace(/\s+/g, '_')}_MediaPlan.pdf`);
};

// =============================================================================
// SPECIALIZED EXPORT FUNCTIONS
// =============================================================================

export const generatePostCampaignPDF = (
  mediaPlan: MediaPlan,
  performanceData?: ExportData['performance']
) => {
  generateMediaPlanPDF(mediaPlan, {
    exportType: 'POST_CAMPAIGN',
    filename: `${mediaPlan.campaign.name.replace(/\s+/g, '_')}_PostCampaign.pdf`,
  });
};

export const generateAttributionPDF = (
  mediaPlan: MediaPlan,
  attributionData?: ExportData['attribution']
) => {
  generateMediaPlanPDF(mediaPlan, {
    exportType: 'ATTRIBUTION_REPORT',
    filename: `${mediaPlan.campaign.name.replace(/\s+/g, '_')}_Attribution.pdf`,
  });
};

export const generatePortfolioPDF = (
  mediaPlan: MediaPlan,
  campaigns?: MediaPlan['campaign'][]
) => {
  generateMediaPlanPDF(mediaPlan, {
    exportType: 'PORTFOLIO_SUMMARY',
    filename: `Portfolio_Summary_${new Date().toISOString().split('T')[0]}.pdf`,
  });
};
