import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { MediaPlan } from '../types';

export const generateMediaPlanPDF = (mediaPlan: MediaPlan) => {
    const doc = new jsPDF();
    const { campaign } = mediaPlan;

    // Title
    doc.setFontSize(20);
    doc.text('Media Plan Export', 14, 22);

    doc.setFontSize(12);
    doc.setTextColor(100);
    doc.text(`Client: ${campaign.advertiser}`, 14, 32);
    doc.text(`Campaign: ${campaign.name}`, 14, 38);
    doc.text(`Budget: $${campaign.budget.toLocaleString()}`, 14, 44);
    doc.text(`Dates: ${campaign.startDate} to ${campaign.endDate}`, 14, 50);

    // Stats
    doc.text(`Total Spend: $${mediaPlan.totalSpend.toLocaleString()}`, 140, 32);
    doc.text(`Remaining: $${mediaPlan.remainingBudget.toLocaleString()}`, 140, 38);

    // Placements Table
    const tableData = campaign.placements.map(p => [
        p.channel,
        p.vendor,
        p.adUnit,
        `${p.startDate} - ${p.endDate}`,
        `$${p.rate.toLocaleString()} / ${p.costMethod}`,
        p.quantity.toLocaleString(),
        `$${p.totalCost.toLocaleString()}`
    ]);

    autoTable(doc, {
        head: [['Channel', 'Vendor', 'Ad Unit', 'Dates', 'Rate', 'Qty', 'Cost']],
        body: tableData,
        startY: 60,
        theme: 'grid',
        styles: { fontSize: 8 },
        headStyles: { fillColor: [124, 58, 237] } // Purple
    });

    // Footer
    const finalY = (doc as any).lastAutoTable.finalY || 60;
    doc.setFontSize(10);
    doc.text('Generated by OmniChannel Media Planner Agent', 14, finalY + 10);

    doc.save(`${campaign.name.replace(/\s+/g, '_')}_MediaPlan.pdf`);
};
